version: '3' # specify docker-compose version

# Define the services/containers to be run
services:
  front: # name of the first service
    image: 'node:13.0-alpine'
    container_name: front
    ports:
        - 127.0.0.1:4200:4200
    volumes:
        - './front:/home/node/app'
    working_dir: /home/node/app
    command: ['sh', '-c', 'npm install && npm run start']
    restart: always

  backend: #name of the second service
    container_name: backend
    build: backend # specify the directory of the Dockerfile
    ports:
      - "3000:3000" #specify ports forewarding
    links:
      - mongo
    depends_on:
      - mongo

  mongo: # name of the third service
    image: mongo # specify image to build container from
    ports:
      - "27018:27017" # specify port forewarding